### ISSUE TITLE
Please clean up your requirements — again.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/monochromy#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 and kevinadhiguna/body-mass-index-calculator#1 and kevinadhiguna/ip-revealer#1 …

Low quality bulk library creation with no use of the referenced libraries is pure spam.  Please correct this.  Heck, that last one is a pointless reimplementation of the stock `host` or `nslookup` commands. Even `ping` would do.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor , I am so grateful for this report. I just pushed the [latest commit](https://github.com/kevinadhiguna/monochromy/commit/69dc4c88c38007915702d4f69cb647e1a531687d) that probably is able to fix that. I hope this helps, thank you !

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) Wave 2! 😀
